P1-Wiki/encyclopedia/urls.py
# urls.py
from django.urls import path # give us the ability to reroute URLSs
from . import views # import any functions we’ve created in views.py.

""" 
    Used to associate views with URLS 

    For each desired URL, add an item to the urlpatterns list that contains a call to the
        path function with two or three arguments: 
        
        1. A string representing the URL path, 
        2. a function from views.py that we wish to call when that URL is visited
        3. (optionally) a name for that path, in the format name="something" 
        
"""

""" 
    After being re-routed from the main url.py (project scope); Django ignores 
        the parts of the URL it has already used in rerouting (localhost:8000/hello/, 
        or all of it) and looked inside our other urls.py file for a pattern that matches 
        the remaining part of the URL.

    Finally Django runs the corresponding function

"""

app_name = "encyclopedia"
# list of url patterns that a user might visit while using our website
# if path = ""; run views.index
urlpatterns = [ 
    path("", views.index, name="index"),
    path("<str:entry>", views.open, name="open"),
    path("search/", views.search, name="search"),
    path("add/", views.add, name="add"),
    path('edit/<str:entry>/', views.edit, name='edit'),
    path('randomPage/', views.randomPage, name='randomPage'),

]

P1-Wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path


""" 
Process: When we access the URL (http://127.0.0.1:8000/) django checks what comes after the 
    base URL and searches this file for for that pattern. 

EX: if pattern = '' (base URL only) => path('', include("encyclopedia.urls")) then:
    Include all of the paths from the urls.py file within our application so
    when a user visits our site they’ll be redirected to the paths inside of our application.
"""

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")) 
]

P1-Wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

P1-Wiki/encyclopedia/views.py
# views.py
from django import forms
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from . import util
import markdown2
import random



""" 
we pass a third argument into the render function here, one that is known as the context. 
    In this context, we can provide information that we would like to have available within 
    our HTML files. This context takes the form of a Python dictionary.

 """
def index(request):
    return render(request, "encyclopedia/index.html", {
        "title": 'Search',
        "heading": 'All Pages',
        "entries": util.list_entries()
    })

def open(request, entry):
    markdown_content = util.get_entry(entry)
    if markdown_content is None:
        return render(request, "encyclopedia/error.html", {
            "message": "Entry not found"
        })

    html_content = markdown2.markdown(markdown_content)
    return render(request, "encyclopedia/entry.html", {
        "title": entry,
        "desc": html_content
    })

def search(request):
    if request.method == 'POST':
        text = request.POST['q']
        print('searching')
        if util.get_entry(text) is not None:
            return render(request, "encyclopedia/entry.html", {
                "title": text,
                "heading": 'All Pages',
                "desc": util.get_entry(text)
            })
        
        else:
            entries = util.list_entries()
            matches = [entry for entry in entries if text.lower() in entry.lower()]
            return render(request, "encyclopedia/index.html", {
                "title": 'Search',
                "heading": 'Search Results',
                "entries": matches,
            })

""" 
Inside this class, we can specify what information we would like to collect from the user, 
    in this case the name of a entry.

We specify that this should be a textual input by writing forms.CharField,

Within this CharField, we specify a label, which will appear to the user when they load the page.
"""

class NewEntryForm(forms.Form):
    entry = forms.CharField(label="New Entry")
    desc = forms.CharField(label="Description", widget=forms.Textarea(attrs={'height': '90vh', 'width': '20%'}))
    

""" 
Add a new entry:
    include NewEntryForm in the context while rendering the add page: 
"""

def add(request):
    # Check if method is POST

    if request.method == "POST":

        # Take in the data the user submitted and save it as form
        form = NewEntryForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the entry from the 'cleaned' version of form data
            entry = form.cleaned_data["entry"]
            desc = form.cleaned_data["desc"]

            if util.get_entry(entry) is not None:
                raise forms.ValidationError('ERROR: Duplicate Entry.')

            # Add the new entry to our list of entrys
            util.save_entry(entry, desc)

            # Redirect user to list of entrys
            return HttpResponseRedirect(reverse("encyclopedia:add"))

        else:

            # If the form is invalid, re-render the page with existing information.
            return render(request, "encyclopedia/add.html", {
                "form": form
            })

    return render(request, "encyclopedia/add.html", {
        "form": NewEntryForm()
    })

class NewEditForm(forms.Form):
    entry = forms.CharField(label="Entry", disabled=True, required=False)
    desc = forms.CharField(label="Description", widget=forms.Textarea(attrs={'height': '90vh', 'width': '20%'}))

def edit(request, entry):
    existing_entry = util.get_entry(entry)
    if existing_entry is None:
        return render(request, "encyclopedia/error.html", {
            "message": "Entry not found"
        })

    if request.method == "POST":
        form = NewEditForm(request.POST)
        if form.is_valid():
            new_desc = form.cleaned_data["desc"]
            util.save_entry(entry, new_desc)
            return HttpResponseRedirect(reverse("encyclopedia:edit", args=[entry]))
    else:
        form = NewEditForm(initial={'entry': entry, 'desc': existing_entry})

    return render(request, "encyclopedia/edit.html", {
        "entry": entry,
        "form": form
    })

def randomPage(request):
    entry = random.choice(util.list_entries())
    return render(request, "encyclopedia/randomPage.html", {
        "entry":  entry
    })

P1-Wiki/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <h1>{{heading}}</h1>
    <form action="{% url 'encyclopedia:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}

P1-Wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit - {{ entry }}
{% endblock %}

{% block body %}
    <h1>Edit - {{ entry }}</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

P1-Wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <a href="{% url 'encyclopedia:edit' entry=title %}">Edit Page</a>
    <h2>{{ desc|safe }}</h2>
{% endblock %}

P1-Wiki/encyclopedia/templates/encyclopedia/index.html
<!-- index.html -->
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    <h1>{{heading}}</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:open' entry=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

P1-Wiki/encyclopedia/templates/encyclopedia/layout.html
<!-- layout.html -->
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    <input type="submit">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

P1-Wiki/encyclopedia/templates/encyclopedia/randompage.html
{% extends "encyclopedia/layout.html" %}
 
{% block title %}
    Encyclopedia
{% endblock %}
 
{% block body %}
    <h1>random</h1>
    <li><a href="{% url 'encyclopedia:open' entry=entry %}">{{ entry }}</a></li>
{% endblock %}